### PR TITLE
Add a .gt1 compiler script

### PR DESCRIPTION
**Pull request by Cwiiis**
This PR makes some small modifications to asm.py and gcl0x.py that makes it easier to use them to build GCL code to transfer over to the gigatron (or use in a gigatron emulator). It outputs in the .gt1 file format.

Two small programs are also added to help test loading code and to provide simpler examples to get started with GCL.

### CODE REVIEW

**Comment by kervinck** [comment]
Ah, thanks! It looks useful. I need to take a closer look this weekend, but it makes sense to me and if I see no critical issues then I will accept it. I just have to figure out how all these GitHub functions work :-)

**Comment by Cwiiis** [comment]
Thanks :) If you have any suggestions for tidying/improvement, let me know and I'll update this request. I've, for the most part, tried to keep this down to the minimal set of changes.

**Comment by kervinck** [comment]
Creative use of the .1.rom file! I will adopt it as-is, because it is immediately useful.

Some path to enlightment:
1. Lets use json instead of pickle (easier too see what is going on)
2. Convert bindings.h into bindings.json. For compatibility, this file should become the formal interface between ROM and GCL programs. The symbol table itself contains a lot of arbitrary stuff.
3. Make the symbol table optional in the command line arguments. If it is not supplied, read bindings.json
[4. Generate bindings.h from bindings.json]

**Comment by Cwiiis** [comment]
Completely agreed, json is much nicer than pickle - and I hadn't even noticed bindings.h, I'm kicking myself a bit now!

That sounds like a nice path forward. I also think making the .0, .1 and .2 roms optional is a good idea and adding another optional output of .gt1 that takes in a start address would be nice, and allow shrinking down compilegcl.py even further. And for good measure, I guess the .asm output could be optional too(?)

**Comment by kervinck** [comment]
No hurry and I can pick it up also. Another thought: now we have found ourselves at a resting place where users need hex dumps of GT1 files instead of GT1 files themselves... We should either have a standalone GT1 to H converter. Or put it in compilegcl.py (Just generate both, unconditionally).

I have a slight preference for integrating it, because it is such a small additional step to a small program already. But I'm aware that it is an entanglement as well, because there are more ways to generate GT1. Another small designer's dilemma.

[Edit: ok, though about it and I will become a purist there. GT1-to-H should be a separate little program]

**Comment by kervinck** [comment]
About making files optional: theloop.py is a little monster. The name is confusing. I haven't used the .0.rom and .1.rom files for ages. The entire setup is idiosyncratic. I abused Python as a way to avoid writing an assembler at all. I used Python notation as a very powerful macro assembler for me, and I needed that, but it is also giving me an ugly and write-only notation for native code. (The reason I have .asm output is because that is how I read back native code to check if I get what I wanted to say.) The goal was always "it must work for me, at this moment, and the only objective is to ship ROM v1".

Now we're in a new phase, and I'm not clinging to it. It has good points. Python -is- a very powerful macro assemble. A lot of intelligence in the ROM comes from it. But it also works in a completely unexpected way for new people to the project. The approach is unconventional. But heck, the whole Gigatron is unconventional :-)

Rather than make things optional, let them become obsolete by new developments. There is a lot I can do to make Python notation for native code simpler. We can simply uncluttered the root directory by moving ROM files in a subdir. One thing what theloop.py should do for the "ROM disk" part is read GT1 files first (now it compiles the from GCL).

Maybe this is the observation: the ROM has two functions: kernel and ROM disk. But now the ROM disk is just an extension of the kernel.

Ok just rambling, no expectations. Just wrapping my head around entering a new phase!

**Pull request merged**
