### PR TITLE
Fix lcc compiler compile error

### PR DESCRIPTION
**Pull request by xopr**
On a clean machine, I came to the discovery that `make lcc` failed; it gave the following set of (similar) errors:
`./build/gt1.c:3840:2: error: ‘for’ loop initial declarations are only allowed in C99 mode`

After research, I came to the conclusion that either **Utils/lcc/src/gt1.md** violates the standard on six occasions, or the makefile needed `CFLAGS=-std=c11` , similar as the root Makefile.
Also, I noted that the variable was referenced incorrectly.

This pull request should fix the compiler error (tested on **RHEL 7.6**, **GNU Make 3.82** and **gcc 4.8.5**

### CODE REVIEW

**Comment by kervinck** [comment]
In this case, I think it's best to make it adhere to ANSI C aka C89. Because all the rest of LCC is ANSI C as well, and LCC only compiles ANSI C. What do you think?

**Comment by kervinck** [comment]
OTOH, if it works, it works... I gooi het er gewoon in!

**Comment by xopr** [comment]
Bedankt!
I like the idea of a lean/old/strict/classic compiler standard, but having a shortcut is probably not bad in the case of a (binary) tool.
Maybe it's worth having a low priority improvement task for it.

**Comment by kervinck** [comment]
It's fine. There are bigger issues with LCC to worry about. I just added a line to #70 for this.

**Pull request merged**
