### PR TITLE
121 migrate from python 2 to 3

### PR DESCRIPTION
**Pull request by TeddyBear06**
From my perspective, it seems pretty ready for Python 3 now, all scripts seems to be fully functionnal (but I still need your review to be 100% sure).

Mainly strings formatters changes.

I did add a verification (line 338 of Core/gcl0x.py) due to Python 3 byte type handling.

I did run tests successfully (both `make test` and `make compiletest`). I diff _compiletest_ outputs from master version Python 2 and my branch version Python 3, they are strictly identicals.

I created a .gitignore to avoid building artefacts to be tracked.

Please let me know if you need something else.

Kind regards,

### CODE REVIEW

**Comment by kervinck** [comment]
Oh wow, that more work than I expected. I wasn't aware that they removed the format operator % as well! Give me 2 or 3 days to look it all through.

**Comment by TeddyBear06** [comment]
Well, the % format operator is not dropped, it's the "old way" of formatting strings in Python 3 (cf. https://docs.python.org/3/tutorial/inputoutput.html#old-string-formatting).

 If you prefer we can keep the old formatting style.

**Comment by kervinck** [comment]
Don't worry, I just have to catch up with the things p3 bring. Is there some guidance from Guido on which method to use?

**Comment by TeddyBear06** [comment]
Well, Guido said that the .format() method is too verbose and suggest to use f-strings in "rescue" (PyCascades2018 https://i.imgur.com/gdteM3Q_d.jpg?maxwidth=640&shape=thumb&fidelity=medium full video here => https://youtu.be/Oiw23yfqQy8).

We can follow is point of view if you prefer, I'm really open.

But I still think .format() is an explicit and robust way of formatting strings :-)
Le 17/11/2019, 23:19 Marcel van Kervinck <notifications@github.com> a écrit:
Don't worry, I just have to catch up with the things p3 bring. Is there some guidance from Guido on which method to use?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kervinck/gigatron-rom/pull/124?email_source=notifications\u0026email_token=AALCTOTO27NL6URZ7FLXVOLQUG7QHA5CNFSM4JOLKU42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEIXXIQ#issuecomment-554793890",
"url": "https://github.com/kervinck/gigatron-rom/pull/124?email_source=notifications\u0026email_token=AALCTOTO27NL6URZ7FLXVOLQUG7QHA5CNFSM4JOLKU42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEIXXIQ#issuecomment-554793890",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kervinck** [comment]
Ok clear. Does he have an argument against the % operator? It's most concise and suitable for the job?

**Comment by kervinck** [comment]
Half year ago I struggled with the LCC port because brew didn't have python 3.6 yet. But now this is is solved. f-strings are indeed better than ''.format(). But I don't know what's the problem with %. The only issue is that python2 will not be supported from 2020 on, so I was expecting only a couple print statements needed brackets.

**Comment by TeddyBear06** [comment]
Ok I see. 

But as I said it just a matter of choice (personnaly the "f" of f-strings lost between a parenthesis and a quote is not really readable).

Let me revert my modifications and just fix print parenthesis still using old string format with % and fix some other typing issues to make all scripts works with Python 3 :-)

Is that okay for you ?

**Comment by kervinck** [comment]
I agree that the f'-modifier isn't the greatest, but I can understand that Guido needed to do something like that. In a simple language that I restarted to design many times over, the '...{expr}...' expansions where the default. Sure I loved it when out of the blue almost the same notation appeared in p3!

To me, ''.format() has feels like exposing implementation externals to the user. It is almost shouting out "hey, did you know these strings are really objects that can do this cool trick?". While the %-notation was already ok'ish and kept things it concise. It's certainly also not perfect, but good enough for simple programs.

So if there's no pending removal of this operator in p3, I would vote for keeping it. This is not enterprise software after all. It is best served by keeping visual clutter down.

**Comment by TeddyBear06** [comment]
> So if there's no pending removal of this operator in p3, I would vote for keeping it. This is not enterprise software after all. It is best served by keeping visual clutter down.

As far as I know, there is no pending removal.

I dig a little more deeper and I found that the django web framework is still [using this notation](https://github.com/django/django/blob/master/django/views/debug.py#L273) so it's more than enough to convince me :-)

```python
v = '%s… <trimmed %d bytes string>' % (v[0:4096], len(v))
```

I'm gonna update my pull request.

**Pull request closed without merging**
