### PR TITLE
Use PROGMEM to store program code and pad pages with 0x00 in Loader

### PR DESCRIPTION
**Pull request by Cwiiis**
Dynamic RAM on the Arduino Uno is limited to 2k, severely limiting the
size of programs that can be sent with the Loader (Snake, for example, is
only just within this size limitation). Use program memory to store
programs, allowing programs to be around 32k.

In addition, loading larger programs (such as Snake) is very unreliable
unless you pad out each page with zeroes, so modify the loader program to
do this.

### CODE REVIEW

**Comment by kervinck** [comment]
Yes, the 2K is a bummer. The model I had in mind has some kind of fixed firmware in the Arduino, and no need for project software on the PC/Laptop. Then it is the same for everyone's platform (Windows/Linux/Mac), and the Arduino IDE does the platform differences. But this doesn't fly (yet) because the Arduino can't gobble up an entire file, and the Arduino IDE can't push a file over the serial link (I think). And embedding it as an Arduino program that must first be flash, that's not nice as an end solution.

Let me organise my mind of what I want to achieve with GT1 files:
1. Programs must be loaded into real Gigatron that has ROM v1
2. Large GT1 files must be handled, even 30K
3. Windows/Linux/Mac must be supported equally well
4. Tutorials for doing this must have a "clicketee-click" level of simplicity.
No typing of commands. No compilation of stuff. No packages to install etc.

I don't see a clear solution yet.

**Comment by Cwiiis** [comment]
Arduino might not really be the best tool for those goals I expect. I think most people who would have an Arduino are ok with the process of flashing it, but I agree it's a shame to have the barrier be so high.

I wonder if you could instead use a Pi or even a PC? You could use a USB->DB9 male serial cable (like this: http://amzn.eu/iPLHh1e) and I suppose you could then write software for the PC to do the transfer straight from a file on disk.

At least with the Pi you can easily read from SD, but I wouldn't say the barrier is really any lower than an Arduino, where at least you don't have to deal with learning to manipulate an OS you might not be familiar with.

With the Arduino, you could create a tool that takes a compiled Arduino binary and patches in a new Gt1 file from disk, but it'd still need to be flashed. It's on my TODO list to hack together an Arduino-powered device that could read gt1 files off an SD card, provide some basic LCD-based selector and an extra pass-through port for a gamepad, I'll let you know how I get on with that!

Back to this PR, I think it might be worth merging or making a change similar to this, at least so that tech-savvy users (which is probably going to be a good proportion of gigatron buyers :)) can semi-easily flash large programs to the device in the interim.

**Comment by kervinck** [comment]
You are totally right. The PROGMEM road has the most immediate value now.
I already pulled in your changes into my local repository.
I will make it consistent with changes I was already making and push it back ASAP.

**Comment by kervinck** [comment]
I woke up early so pushed it after some simplifications. Hope I copy pasted the right magic git spells and didn't poison anything.

Yesterday this cute PS/2-TTL adapter arrived: https://www.adafruit.com/product/1136
It costs $17.95, but with shipping, import duties, sales tax and handling fees for those (robbers!), it put me down 46.20 euros ($55.34). Welcome to the Netherlands.

**Comment by Cwiiis** [comment]
Cool, it'll be neat to be able to do some coding on the gigatron itself :) I empaphise very much with the cost of getting things from adafruit.com, I have the same issues here too (and not being able to ship batteries is also a bit irritating)

Regarding this merge, I see you removed the padding part of it - does transferring large files work for you? (using compilegcl.py on Snake is how I usually test) For me if I don't pad each touched page out with zeroes, I get crashing/weird behaviour in both the emulator and on device. I've not tried to dig into why this is, but I suspect you'd have better insight here :)

**Comment by Cwiiis** [comment]
Oh, as an aside (and sorry to pollute this discussion), but I just created a VIM syntax highlighting file for GCL which I'm finding extremely useful - is this something worth having in the repository?

**Comment by kervinck** [comment]
The padding is done by over-allocating the send buffer. It is 5*60 = 300 bytes. My idea is that the overlength (256->300) eliminates the conditionals.

YES GIVE ME VIM HIGHLIGHTING

I started to use vi in 1993 and I still feel like a beginner.
But then, the reason I bought my first MacBook Pro is because it had vim integrated (true story).
[SMK](https://chessprogramming.wikispaces.com/Stefan%20Meyer-Kahlen) laughed at me when I told him I didn't use highlighting.

**Pull request merged**
