### PR TITLE
Replaced old lcc with glcc 1.5

### PR DESCRIPTION
**Pull request by lb3361**
Following a discussion with at67 a couple months ago.

- removed Libs and Utils/lcc which was broken.
- created Compilers/glcc with GLCC_RELEASE_1.5
- created placeholder Compilers/gtbasic

Lots of files...

### CODE REVIEW

**Comment by at67** [comment]
As previously discussed, could you please move Libs and Utils/lcc into an Archive/lcc folder, (Archive should be under root in the same way that Compilers is). Cheers.
~~~
Compilers
    |
    +---glcc
    |
    +---gtBASIC

Archive
    |
    +---lcc
          |
          +---Libs
          |
          +---Utils
                |
                +---lcc
~~~

**Comment by lb3361** [comment]
Will do.
- Leon

**Comment by lb3361** [comment]
Just added the 'Archive' directory as requested, with terse Readme.md files.

**Comment by at67** [comment]
Cheers.

**Pull request merged**
