### PR TITLE
[Gigatron Mac]Rewrite keyboard handling to fix sticking keys

### PR DESCRIPTION
**Pull request by tbraun-de**
... and release version 0.1.3 as .dmg file

### CODE REVIEW

**Comment by kervinck** [comment]
What a treat, a .dmg file and an icon. I promoted it to my Desktop.

In the default settings, it seems to run at about half of the real-time speed, without sound. Is that expected? If not, we should put some effort in understanding the mechanism behind it.

**Comment by tbraun-de** [comment]
Thank you, I'm glad you like it! 

I'd really like to investigate why the emulator is not running in real time on your machine. Could you please check in activity monitor how much of your CPU the Gigatron Mac process is using when it's running in the foreground (so the gigatron mac windows has focus)?

Bildschirmfoto 2019-03-16 um 20 31 04

**Comment by kervinck** [comment]
Here's a screenshot. The number of threads varies a bit. The fans spin up.

Screenshot 2019-03-17 at 21 43 36

**Comment by kervinck** [comment]
I was using the emulator today to help debugging our new C compiler, when I noticed that the RAM watch shows something interesting: the last byte in every page is shown as FF. Is this a bug?

Screenshot 2019-05-04 at 18 00 34

**Comment by tbraun-de** [comment]
You are right, thank your for pointing it out! A typical off-by-one error :-) I'll create a pull request with a fix.

**Pull request merged**
