### PR TITLE
Add WORD read/write (DEEK/DOKE) from address to GCL

### PR DESCRIPTION
**Pull request by Cwiiis**

### CODE REVIEW

**Comment by Cwiiis** [comment]
This adds 16-bit read/write to pointers - I really needed deek for some code I'm writing, but seeing as adding that wasn't a big deal, I went ahead and added doke too (which I expect may well come in handy). Note though that I haven't really tested doke, so though it looks right at a glance, certainly this code needs to be looked at :)

**Comment by Cwiiis** [comment]
I've since tested doke and it works fine. These are pretty invaluable for saving space when copying lots of memory around :)

**Comment by kervinck** [comment]
It is fine with me to put this back in gcl0x.
";" is the right operator for DEEK. I would like to see ":" for DOKE. So we have . , for byte pointer operations and : ; for word pointers.

There is a conflict with address directives: "$0400:", but the compiler treats these differently, so I expect @ can be changed into : without breaking anything. Could you try?

I realise there will be some non-orthogonality, because "\var:" doesn't do what you would expect. But there are more such issues in the gcl0x notation and it is the reason gcl1 needs to rethink these anyway.

**Comment by Cwiiis** [comment]
This would conflict, wouldn't it? The condition on line 200 would catch '<number>:' and line 261 would never get reached? So you'd never be able to do something like '$FFFF $0800:' to write a word to video memory?

**Comment by Cwiiis** [comment]
I guess you could mandate that address directives happen only at the beginning of a line and that dokes are only valid not at the beginning of a line, and that would open up doke without breaking any of the existing GCL in the repository, but I think that's surprising behaviour that could easily trip you up... Alternatively, maybe '::' for doke, or '~'?

**Comment by kervinck** [comment]
I expect it to work because in gcl0x.py <number>+<operator> is internally represented differently from <name>+<operator>. I want to change the address directives in gcl1, but not sure how yet (or I decided and wrote it down somewhere but forgot)

**Comment by Cwiiis** [comment]
Ah, of course, I forgot that it needs to be a zero-page address - I've changed the operator to ':' and it works fine (though it does stop you from using zero-page address directives).

**Comment by kervinck** [comment]
I think that was a difficult way of saying that 'con' and 'var' can't have a value at the same time. The word parser does that. Many operators work differently depending on having a name or an integer operand...

**Comment by Cwiiis** [comment]
Right, I get it now (I think) - so you're suggesting that it isn't worth having the 'i:' notation (for writing the word in \vAC to the address specified in the given zero-page address) at the cost of zero-page address directives? Admittedly, I don't think I'd ever use that, I just added it for symmetry, but do zero-page address directives actually work anyway? (and if so, would it be meaningful to use them?)

**Comment by kervinck** [comment]
I integrated the changes, also keeping the con > 0xff condition. I was planning to revert it, but I can see that it brings more of gcl1 into gcl0x and there is no practical drawback.

Restoring some sense of orthogonality is gcl1's concern. I really like the operator group "." ":" ";" ":" and the address directive will have to change there.

Snake would have benefitted from DOKE for writing the blocks, but it didn't exist at the time.

**Comment by kervinck** [comment]
FYI: I revisited this today. The 'i:' we added with this pull request turned out to be a duplicate of the 'i=' that was already in there. I didn't realise that until much later. After updating the GCL documentation today, I conclude it is best to deprecate the older notation, and keep yours. ('i=' will still work, but gives a warning now.)

Details in https://github.com/kervinck/gigatron-rom/commit/a77bce30b1e41748a183e67b27c74272a810bb5f

**Pull request merged**
