### PR TITLE
Add experimental implementation of GtForth

### PR DESCRIPTION
**Pull request by hsnaves**
This pull request contains:
- A patch to vasm.py fixing a few bugs and adding some features that are used by GtForth.vasm.py;
- An implementation of an emulator/simulator for the vCPU that can be used within Python itself;
- The source code of GtForth (together with the corresponding compiled GT1 file). The source code was written using the vasm assembler;

### CODE REVIEW

**Review by at67 — CHANGES_REQUESTED** [review]
Have you verified that your changes to Core/vasm.py still assemble all previous source code correctly? Marcel designed and implemented vasm.py and I am hesitant, (even though your changes from a cursory glance look good), to introduce any changes/updates to his work unless they have been 100% verified and do not break or cause incompatibilities with any of his or anyone else's old code.

Core/vcpu.py should be moved into your own directory, there are multiple emulators, assemblers, compilers, tools etc created by multiple authors, each author's tools lives in his own directory.

Cheers.

**Comment by hsnaves** [comment]
Well, I tested assembler a few times, and it produces identical GT1 output files whenever the source code was compatible with both versions. And, as far as I could find, there is only one use of vasm.py in the entire repository (in Apps/Blinky/Blinky2.vasm.py).

```
[hnaves@blade15 gigatron-rom]$ git grep " vasm " | grep import 
Apps/Blinky/Blinky2.vasm.py:from vasm import *
Contrib/hsnaves/GtForth/GtForth.vasm.py:from vasm import *
Core/vasm.py:# SYNOPSIS: from vasm import *
```
I am not sure if there is any other code somewhere else... Is there any other Git repository that I am not aware of?

Regarding the move of vcpu.py, I can do that.

**Comment by hsnaves** [comment]
I forced push a new set of commits, to keep a clean history.

**Comment by at67** [comment]
There is no other repo that I am aware of. 

Thanks for applying the change to vcpu.py. 

I'll have a proper look at your changes to vasm.py tonight and merge them when I get back from work, (heading off in 3 mins), cheers.

**Review by at67 — APPROVED** [review]
Cheers.

**Pull request merged**
