### PR TITLE
Add new gigatron program: maze builder

### PR DESCRIPTION
**Pull request by tbraun-de**
Hi Marcel, I've written a first gigatron program in gigatron assembly and would like to share it with the world :-) Regards, Tobias

### CODE REVIEW

**Comment by kervinck** [comment]
Super neat!

**Comment by kervinck** [comment]
Please feel free to show it off on the forum, and share some of your learning experiences while making this?

**Comment by kervinck** [comment]
```
rand_dir        LDWI    SYS_Random_34              ; randomize a new direction
	                STW     0x22
	                SYS     34
```
Heads up: The SYS invocation here is probably a bug: I expect the operand to be 270-34/2 = 253

I'm too tired now to figure out what is happening for just starting at it, but possibly this results in a bad VGA signal. The emulators don't catch that well. Real monitors are sensitive to correct timing.. I test it on a real Gigatron tomorrow or this weekend...

**Comment by kervinck** [comment]
Hello Tobias. I just tested maze.gt1 on real hardware. My LCD monitor that is most critical on correct timing doesn't like the video signal. This is what I expected. "SYS 34" will essentially always allow the SYS_Random_34 call to run, even if there isn't sufficient time in the current time slice to do so. The result is inconsistent video timing.

**Comment by tbraun-de** [comment]
Hi Marcel, thank you very much for the feedback! I did not really know how to use the SYS call properly :-) I've sent a pull request containing the suggested fix to you.

**Comment by kervinck** [comment]
Great! I spotted it more or less by accident. I didn't do a full review of the program...

**Pull request merged**
