### PR TITLE
xopr's initial repo (NetTerm)

### PR DESCRIPTION
**Pull request by xopr**
This pull request is to order my snippets into the Contrib directory and currently contains 'NetTerm': a first attempt of a (serial) network terminal

### CODE REVIEW

**Comment by kervinck** [comment]
Hmm, I believe I added a comment this morning about the cycle counting annotation. But I can't find it back now. @xopr: did you get any notification of that?

**Comment by xopr** [comment]
@kervinck I haven't seen anything passing by (also, not in the mail).
If you mean that I'm pushing the limits of the amount of instructions on the SYS call: I'm aware of it (and actually even need a couple more cycles); any help on optimizing the `SYS_VDrawWord` call is very welcome.

I did notice that the devrom was updated and the patch cannot be applied; I'll have to look into that once I have access to my machine.

**Comment by kervinck** [comment]
I must have forgotten to hit 'Comment'. In short:

- The cycle annotation is inconsistent in a couple of places. For example, '19' followed by '21'.
- SYS_VDrawWord_137 can never be a valid name, because the number of cycles must be even.
- The return value seems wrong. When returning to REENTER, there are 4 instructions more from "jmp y,XXX" to "NEXT". That means that the return value in AC should be equal to -((N+4)/2), where N is the cycle annotation of the jmp instruction itself.

I think its ok to put it in the dev.py so we can maintain and improve it towards a next release ROM. As long as you don't include it in interface.json, we can do with it whatever we see fit. Once it enters interface.json, it becomes a "contract", so lets postpone that. Just make a local declaration in the code that uses it.

I would like to help optimise it once I can find a gap in my schedule. If it's really longer that 134 cycles, it won't run in video mode 0. That is because the vCPU time slices during vertical blank interval are a bit short.

**Comment by xopr** [comment]
Thanks for the strong pointers: I fixed the numbering and noticed that it currently is exactly 134 cycles (if I include the 4 instructions after the last `jmp(Y,'REENTER')` ).

The downside is that the "shift down" for some charachters and dotting the 'j' is not in there, but that is more of less an aesthetic bug.

I annotated the pen/background `ld` instructions after branching with `a` and `b` to reduce confusion (I was confused myself due to the opcode prefetch)

As for the optimization: I quickly looked into whether shifting the bits would be more efficient in the long run (compared to loading and masking the desired bit, but I had the impression that it took more cycles.
Maybe it's an idea to take a different branch on video modes that have more cycles available.
The current solution might not be pretty, but it works for now :)  

I'll prepare another pull request to tick off the bullet list.

**Pull request merged**
