### PR TITLE
img2gasm.py - Create gigatron loading screens from JPG/PNG image files

### PR DESCRIPTION
**Pull request by tbraun-de**
Another pull request, I was quite busy today :-) 
This time, it's a python tool I wrote for creating loading screens for Gigatron programs. 
Two sample files are included.

### CODE REVIEW

**Comment by kervinck** [comment]
A space shuttle :-)

**Comment by tbraun-de** [comment]
Yup :-) another piece of high-tech right from the 80s

**Comment by kervinck** [comment]
I was a bit surprised nobody noticed the issue with BabelFish on Arduino Uno (I fixed it today). It has been in there for months. Are you using this path already, or is your work mostly in the emulators?

**Comment by tbraun-de** [comment]
I work mostly in emulators. For uploading code to my real gigatron, I'm using an arduino micro (don't have an arduino uno at hand). 
I've had no experience with arduino at all before gigatron, my only embedded experience is a little bit of the microchip PIC 16F series. Still, I was surprised how easy it was to get the arduino up and running with the gigatron.

**Comment by kervinck** [comment]
Yes, Arduino isn't hard. But we notice it's still a bit of a barrier for many people. That's why I hope we can get an SDCard interface working at some point. BTW, this silly BabelFish bug was timing-related. It only affected the Uno, for as far as I can tell.

**Comment by tbraun-de** [comment]
I think so, yes. At least for the micro, I didn't notice any issues at all. 

Regarding the SDcard thread: I've followed the thread in the gigatron forums and I'm looking forward to you guys figuring it out! What I've understood so far sounds quite promising. 

One question that just came to my mind: I've had quite a hard time in finding detailed documentation about how to write gigatron programs. Have you thought about opening up a wiki (either the wiki here in GitHub or a self-hosted one like wiki.gigatron.io) where we all could contribute and collect the different bits and pieces of documentation that are available? In fact, a rather important part that helped me understanding some commands in detail was http://www.iwriteiam.nl/PGigatron.html which I found by accident.

**Comment by kervinck** [comment]
I should be working on that instead of the SPI interface. But sometimes an itch must be scratched.

A wiki is a great idea, but it will duplicate information so I'm a bit hesitant. They work best if one maintainer puts a lot of effort in them to keep it structured, and I also lack time.

The forum worked for the earliest adopters. In fact, it was introduced as a follow-up for GitHub threads that got too long :-) Most stuff is now described in one place or another, but you have to know where. Sometimes the forum, sometimes the website, sometimes the GitHub repo, sometimes elsewhere entirely. There's so much now after less than a year, it is easy to overlook something.

So I was thinking of making a single "how to do this" list, with typical howto questions and just links to where they were answered before. Perhaps on the website, starting from the page now called "Tutorials" (https://gigatron.io/?page_id=574). Or perhaps such a page as a sticky post in the forum.

**Pull request merged**
