### PR TITLE
[BabelFish] Don't include TinyBASIC in small microcontrollers

### LINKED ISSUE #89: Limited Program Memory for BabelFish in ATTiny85
The current GT1 files loaded on the ATTiny85 (flash size < 10,000) includes TinyBASIC and leaves only 156 bytes of PROGMEM left for new feature development.

Since TinyBASIC is included in ROMv3, it should now only be loaded in larger devices (flash size >= 10,000).

This change would require Pluggy McPlugface users with < ROMv3 to remain on an earlier version of BabelFish for TinyBASIC.

### PR DESCRIPTION
**Pull request by ryanohoro**
Closes #89

### CODE REVIEW

**Comment by kervinck** [comment]
I think the change should be such that the ATtiny85 object code doesn't change, because that is what we'll ship for the time being and document in the printed manual. Our current stock is already programmed and printed...

**Comment by kervinck** [comment]
I think I prefer to keep TinyBASIC in the ATtiny85 target of the main repro, because it's the only way to load BASIC on systems ROM v1 and ROM v2 (and because that feature is documented). You can always make your own target that excludes it?

**Comment by kervinck** [comment]
Ctrl-F3 is another documented feature that changes with this pull request. (It becomes Ctrl-F2)

**Comment by ryanohoro** [comment]
Ah, yes. The shortcut makes sense. Thanks for looking at this!

I'm trying to build some wishlist items for BabelFish, like caps lock, and LED control, but as I hinted at in the issue #89, there's just no room for even basic LED control.

I can probably refactor the keymap and save 50 bytes or so, but the plain truth is there can be no new features for Pluggy until more program memory can be freed up.

Since, as you mention, all the v3 kits have been flashed, it seems kind of pointless to keep TinyBasic in Pluggy McPlugface going forward. Those looking for new features can pull them out of master for ROMv3+, and ROMv1-2 users can continue to use the older versions of BabelFish.

I'm happy to take other suggestions for freeing up program memory, but this seems to be a good time to free up the 3073 bytes TinyBasic takes up.

**Comment by kervinck** [comment]
I see, that wasn't clear from the issue description. It just removed two documented functions without adding anything for the user.

Of course the sources should also reflect what we actually ship out. And the object files need to updated along the way. They should go hand in hand with the sources:

```
-rw-r--r--  1 marcelk  staff  22706 Sep 29  2018 BabelFish.ATtiny85.hex
-rw-r--r--  1 marcelk  staff   8064 Sep 29  2018 BabelFish.ATtiny85.bin
```

One idea is to fork and freeze the old version in the archive, and make changes to an active development version. That's how we do that for the ROM files as well: we keep all released versions out there visible in the main branch.

From a practical point of view, we have "Pluggies" flashed and packed that probably good for the the next 6-12 months. So any new software version will enter the series after that. That gives us plenty of time to prepare any new version with new functionality. If TinyBASIC must go, so be it...

P.S: My time has recently become limited due to changed personal circumstances.  I won't be able spend _too much_ active time on improving old things. The memory card expander has priority, and that may take until the end of this year or longer in the current situation. But if you can help out, why not!

**Comment by kervinck** [comment]
I just saw your tweet on this issue, and it makes me sad to be mocked like that. For the record: Tiny BASIC is case insensitive, and recent applications like Microchess and the Apple1 mockup convert every key stroke to upper case themselves (so holding the shift is not needed).

**Comment by ryanohoro** [comment]
No mocking intended. I apologize if it came across that way. 

I shared the Gigatron on Twitter and tagged the Gigatron account because I appreciate this work so much. I purchased a kit, very much liked what the Gigatron does, looked at the features that needed to be worked on, and I'm offering to help support the project with my time.

I understand that this is a challenging project due to obvious limits of the hardware, and I find these kinds of things enjoyable.

I will close this PR for now, and return any needed discussion to the issue for this PR #89

**Pull request closed without merging**
